apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
    app.kubernetes.io/connects-to: secured-sso
  labels:
    app.kubernetes.io/part-of: secured-http-example
    app.kubernetes.io/name: secured-http-service
    app.kubernetes.io/component: frontend
    app.openshift.io/runtime: rh-spring-boot
    app.openshift.io/runtime-version: ${spring-boot.version}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}
